// client/src/pages/AdminDashboard.tsx
import { useAuthContext } from "@/contexts/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import { Users, CreditCard, TrendingUp, AlertCircle, BarChart3, Settings, Search, Filter, MoreHorizontal, Eye, Edit, Trash2, Download, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useState } from "react";

interface StatCard {
  title: string;
  value: string | number;
  change: string;
  icon: React.ReactNode;
  color: string;
}

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  status: "active" | "pending" | "suspended";
  joinedDate: string;
  contributions: string;
}

interface Loan {
  id: string;
  member: string;
  amount: string;
  status: "pending" | "approved" | "rejected" | "active";
  type: string;
  date: string;
}

function AdminDashboardContent() {
  const { user, logout } = useAuthContext();
  const [activeTab, setActiveTab] = useState("overview");
  const [searchQuery, setSearchQuery] = useState("");

  const stats: StatCard[] = [
    {
      title: "Total Members",
      value: "50,234",
      change: "+12% from last month",
      icon: <Users className="w-6 h-6" />,
      color: "blue",
    },
    {
      title: "Active Loans",
      value: "12,456",
      change: "+8% from last month",
      icon: <CreditCard className="w-6 h-6" />,
      color: "green",
    },
    {
      title: "Total Contributions",
      value: "$2.5M",
      change: "+15% from last month",
      icon: <TrendingUp className="w-6 h-6" />,
      color: "emerald",
    },
    {
      title: "Pending Approvals",
      value: "342",
      change: "Requires attention",
      icon: <AlertCircle className="w-6 h-6" />,
      color: "orange",
    },
  ];

  const colorMap = {
    blue: "bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400",
    green: "bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400",
    emerald: "bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400",
    orange: "bg-orange-100 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400",
  };

  // Sample users data
  const users: User[] = [
    { id: "USR-001", name: "Akinola Ojo", email: "akinola@email.com", role: "member", status: "active", joinedDate: "2024-01-15", contributions: "$5,200" },
    { id: "USR-002", name: "Chioma Nwosu", email: "chioma@email.com", role: "member", status: "active", joinedDate: "2024-02-20", contributions: "$8,450" },
    { id: "USR-003", name: "Emeka Okonkwo", email: "emeka@email.com", role: "admin", status: "active", joinedDate: "2023-11-10", contributions: "$12,000" },
    { id: "USR-004", name: "Fatima Abdullahi", email: "fatima@email.com", role: "member", status: "pending", joinedDate: "2024-03-01", contributions: "$0" },
    { id: "USR-005", name: "Ibrahim Adeyemi", email: "ibrahim@email.com", role: "member", status: "active", joinedDate: "2024-01-28", contributions: "$3,750" },
    { id: "USR-006", name: "Joyce Ogundimu", email: "joyce@email.com", role: "member", status: "suspended", joinedDate: "2023-09-05", contributions: "$1,200" },
  ];

  // Sample loans data
  const loans: Loan[] = [
    { id: "LN-2024-001", member: "Akinola Ojo", amount: "$5,000", status: "approved", type: "Personal", date: "2024-03-10" },
    { id: "LN-2024-002", member: "Chioma Nwosu", amount: "$12,500", status: "pending", type: "Business", date: "2024-03-12" },
    { id: "LN-2024-003", member: "Emeka Okonkwo", amount: "$3,000", status: "active", type: "Emergency", date: "2024-02-28" },
    { id: "LN-2024-004", member: "Fatima Abdullahi", amount: "$8,000", status: "pending", type: "Education", date: "2024-03-14" },
    { id: "LN-2024-005", member: "Ibrahim Adeyemi", amount: "$2,500", status: "rejected", type: "Personal", date: "2024-03-08" },
    { id: "LN-2024-006", member: "Joyce Ogundimu", amount: "$15,000", status: "active", type: "Business", date: "2024-01-20" },
  ];

  const statusColors = {
    pending: "bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400",
    approved: "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400",
    rejected: "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400",
    active: "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400",
    suspended: "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400",
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950">
      {/* Header */}
      <header className="bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
              Admin Dashboard
            </h1>
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Welcome back, {user?.name || "Admin"}
            </p>
          </div>
          <div className="flex items-center gap-4">
            <Button variant="outline" size="sm">
              <Settings className="w-4 h-4 mr-2" />
              Settings
            </Button>
            <Button
              onClick={logout}
              variant="outline"
              size="sm"
              className="text-red-600 dark:text-red-400"
            >
              Logout
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Quick Stats */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {stats.map((stat, index) => (
            <div
              key={index}
              className="bg-white dark:bg-slate-900 rounded-lg shadow p-6 border border-slate-200 dark:border-slate-800"
            >
              <div className="flex items-start justify-between mb-4">
                <div>
                  <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                    {stat.title}
                  </p>
                  <p className="text-3xl font-bold text-slate-900 dark:text-white mt-2">
                    {stat.value}
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${colorMap[stat.color as keyof typeof colorMap]}`}>
                  {stat.icon}
                </div>
              </div>
              <p className="text-xs text-slate-600 dark:text-slate-400">
                {stat.change}
              </p>
            </div>
          ))}
        </div>

        {/* Tabs */}
        <div className="bg-white dark:bg-slate-900 rounded-lg shadow border border-slate-200 dark:border-slate-800">
          <div className="border-b border-slate-200 dark:border-slate-800">
            <div className="flex">
              {["overview", "users", "loans", "reports"].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-6 py-4 font-medium text-sm transition-colors ${
                    activeTab === tab
                      ? "text-blue-600 dark:text-blue-400 border-b-2 border-blue-600 dark:border-blue-400"
                      : "text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
                  }`}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>
          </div>

          <div className="p-6">
            {activeTab === "overview" && (
              <div className="space-y-6">
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                  Platform Overview
                </h3>
                <div className="grid md:grid-cols-2 gap-6">
                  {/* Member Growth Chart */}
                  <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h4 className="font-medium text-slate-900 dark:text-white mb-4">Member Growth</h4>
                    <div className="h-48 flex items-end justify-between gap-2">
                      {[35, 45, 55, 62, 78, 85, 92, 88, 95, 100, 110, 118].map((height, i) => (
                        <div key={i} className="flex-1 flex flex-col items-center gap-1">
                          <div 
                            className="w-full bg-blue-500 dark:bg-blue-600 rounded-t"
                            style={{ height: `${height}%` }}
                          />
                          <span className="text-xs text-slate-500 dark:text-slate-400">
                            {["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][i]}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                  {/* Loan Disbursement Chart */}
                  <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <h4 className="font-medium text-slate-900 dark:text-white mb-4">Loan Disbursements</h4>
                    <div className="h-48 flex items-end justify-between gap-2">
                      {[65, 72, 68, 80, 75, 88, 95, 90, 102, 115, 125, 135].map((height, i) => (
                        <div key={i} className="flex-1 flex flex-col items-center gap-1">
                          <div 
                            className="w-full bg-emerald-500 dark:bg-emerald-600 rounded-t"
                            style={{ height: `${height}%` }}
                          />
                          <span className="text-xs text-slate-500 dark:text-slate-400">
                            {["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][i]}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                
                {/* Recent Activity */}
                <div className="mt-8">
                  <h4 className="font-medium text-slate-900 dark:text-white mb-4">Recent Activity</h4>
                  <div className="space-y-3">
                    {[
                      { action: "New member registered", user: "Fatima Abdullahi", time: "2 minutes ago", type: "user" },
                      { action: "Loan approved", user: "Akinola Ojo - $5,000", time: "15 minutes ago", type: "loan" },
                      { action: "Contribution received", user: "Chioma Nwosu - $500", time: "1 hour ago", type: "payment" },
                      { action: "KYC verified", user: "Ibrahim Adeyemi", time: "3 hours ago", type: "kyc" },
                    ].map((activity, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800/50 rounded-lg">
                        <div>
                          <p className="text-sm font-medium text-slate-900 dark:text-white">{activity.action}</p>
                          <p className="text-xs text-slate-500 dark:text-slate-400">{activity.user}</p>
                        </div>
                        <span className="text-xs text-slate-500 dark:text-slate-400">{activity.time}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {activeTab === "users" && (
              <div className="space-y-4">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                    User Management
                  </h3>
                  <div className="flex items-center gap-2">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                      <Input 
                        placeholder="Search users..." 
                        className="pl-9 w-64"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                      />
                    </div>
                    <Button variant="outline" size="sm">
                      <Filter className="w-4 h-4 mr-2" />
                      Filter
                    </Button>
                    <Button size="sm">
                      <Download className="w-4 h-4 mr-2" />
                      Export
                    </Button>
                  </div>
                </div>
                
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-slate-200 dark:border-slate-700">
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">User ID</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Name</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Email</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Role</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Status</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Contributions</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {users
                        .filter(u => u.name.toLowerCase().includes(searchQuery.toLowerCase()) || u.email.toLowerCase().includes(searchQuery.toLowerCase()))
                        .map((user) => (
                        <tr key={user.id} className="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50">
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white">{user.id}</td>
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white font-medium">{user.name}</td>
                          <td className="py-3 px-4 text-sm text-slate-600 dark:text-slate-400">{user.email}</td>
                          <td className="py-3 px-4 text-sm text-slate-600 dark:text-slate-400 capitalize">{user.role}</td>
                          <td className="py-3 px-4">
                            <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${statusColors[user.status as keyof typeof statusColors] || "bg-gray-100 text-gray-700"}`}>
                              {user.status}
                            </span>
                          </td>
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white">{user.contributions}</td>
                          <td className="py-3 px-4">
                            <div className="flex items-center gap-1">
                              <Button variant="ghost" size="icon" className="w-8 h-8">
                                <Eye className="w-4 h-4" />
                              </Button>
                              <Button variant="ghost" size="icon" className="w-8 h-8">
                                <Edit className="w-4 h-4" />
                              </Button>
                              <Button variant="ghost" size="icon" className="w-8 h-8 text-red-500">
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                
                <div className="flex items-center justify-between pt-4">
                  <p className="text-sm text-slate-600 dark:text-slate-400">Showing 1-6 of 50,234 users</p>
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" disabled>Previous</Button>
                    <Button variant="outline" size="sm">Next</Button>
                  </div>
                </div>
              </div>
            )}

            {activeTab === "loans" && (
              <div className="space-y-4">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                    Loan Management
                  </h3>
                  <div className="flex items-center gap-2">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                      <Input 
                        placeholder="Search loans..." 
                        className="pl-9 w-64"
                      />
                    </div>
                    <Button variant="outline" size="sm">
                      <Filter className="w-4 h-4 mr-2" />
                      Filter
                    </Button>
                    <Button size="sm">
                      <Download className="w-4 h-4 mr-2" />
                      Export
                    </Button>
                  </div>
                </div>
                
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-slate-200 dark:border-slate-700">
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Loan ID</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Member</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Amount</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Type</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Date</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Status</th>
                        <th className="text-left py-3 px-4 text-sm font-medium text-slate-600 dark:text-slate-400">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {loans.map((loan) => (
                        <tr key={loan.id} className="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50">
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white">{loan.id}</td>
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white font-medium">{loan.member}</td>
                          <td className="py-3 px-4 text-sm text-slate-900 dark:text-white font-medium">{loan.amount}</td>
                          <td className="py-3 px-4 text-sm text-slate-600 dark:text-slate-400">{loan.type}</td>
                          <td className="py-3 px-4 text-sm text-slate-600 dark:text-slate-400">{loan.date}</td>
                          <td className="py-3 px-4">
                            <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${statusColors[loan.status as keyof typeof statusColors] || "bg-gray-100 text-gray-700"}`}>
                              {loan.status}
                            </span>
                          </td>
                          <td className="py-3 px-4">
                            <div className="flex items-center gap-1">
                              <Button variant="ghost" size="icon" className="w-8 h-8">
                                <Eye className="w-4 h-4" />
                              </Button>
                              <Button variant="ghost" size="icon" className="w-8 h-8">
                                <Edit className="w-4 h-4" />
                              </Button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                
                <div className="flex items-center justify-between pt-4">
                  <p className="text-sm text-slate-600 dark:text-slate-400">Showing 1-6 of 12,456 loans</p>
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" disabled>Previous</Button>
                    <Button variant="outline" size="sm">Next</Button>
                  </div>
                </div>
              </div>
            )}

            {activeTab === "reports" && (
              <div className="space-y-4">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                    Reports & Analytics
                  </h3>
                  <Button size="sm">
                    <Download className="w-4 h-4 mr-2" />
                    Generate Report
                  </Button>
                </div>
                
                <div className="grid md:grid-cols-3 gap-4">
                  {[
                    { title: "Monthly Summary", desc: "Overview of all activities", date: "March 2024" },
                    { title: "Loan Portfolio", desc: "Detailed loan analysis", date: "Q1 2024" },
                    { title: "Member Contributions", desc: "Contribution trends report", date: "March 2024" },
                    { title: "Financial Statements", desc: "Income & expenditure", date: "February 2024" },
                    { title: "Risk Assessment", desc: "Loan risk analysis", date: "March 2024" },
                    { title: "Compliance Report", desc: "Regulatory compliance status", date: "Q1 2024" },
                  ].map((report, i) => (
                    <div key={i} className="p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:border-blue-500 dark:hover:border-blue-500 transition-colors cursor-pointer">
                      <h4 className="font-medium text-slate-900 dark:text-white">{report.title}</h4>
                      <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">{report.desc}</p>
                      <div className="flex items-center justify-between mt-3">
                        <span className="text-xs text-slate-500 dark:text-slate-400">{report.date}</span>
                        <Download className="w-4 h-4 text-slate-400" />
                      </div>
                    </div>
                  ))}
                </div>
                
                <div className="mt-8">
                  <h4 className="font-medium text-slate-900 dark:text-white mb-4">Quick Stats Export</h4>
                  <div className="grid md:grid-cols-4 gap-4">
                    <Button variant="outline" className="justify-start">
                      <BarChart3 className="w-4 h-4 mr-2" />
                      Member Statistics
                    </Button>
                    <Button variant="outline" className="justify-start">
                      <BarChart3 className="w-4 h-4 mr-2" />
                      Loan Statistics
                    </Button>
                    <Button variant="outline" className="justify-start">
                      <BarChart3 className="w-4 h-4 mr-2" />
                      Financial Summary
                    </Button>
                    <Button variant="outline" className="justify-start">
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Refresh All Data
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

export default function AdminDashboard() {
  return (
    <ProtectedRoute requiredRole={["admin", "super_admin"]}>
      <AdminDashboardContent />
    </ProtectedRoute>
  );
}

// client/src/pages/AdminDashboard.vue
<template>
  <div class="min-h-screen flex flex-col">
    <Navigation />

    <div class="flex-1 p-4 sm:p-8 max-w-7xl mx-auto w-full">
      <h1 class="text-4xl font-bold mb-8">Admin Dashboard</h1>

      <div v-if="loading" class="text-center py-12">
        <div class="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        <p class="mt-4 text-slate-600">Loading admin dashboard...</p>
      </div>

      <div v-else class="space-y-8">
        <!-- Admin Stats -->
        <div class="grid md:grid-cols-4 gap-4">
          <StatCard title="Total Members" :value="stats.totalMembers" icon="Users" />
          <StatCard title="Total Loans" :value="stats.totalLoans" icon="Briefcase" />
          <StatCard title="Total Contributions" :value="`$${stats.totalContributions.toLocaleString()}`" icon="TrendingUp" />
          <StatCard title="System Health" :value="stats.systemHealth + '%'" icon="CheckCircle" />
        </div>

        <div class="grid md:grid-cols-2 gap-8">
          <!-- Pending Loan Approvals -->
          <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
            <h2 class="text-2xl font-bold mb-4 flex items-center">
              <Briefcase class="w-6 h-6 mr-2 text-blue-600" />
              Pending Loan Approvals
            </h2>
            <div v-if="pendingLoans.length === 0" class="text-center py-8 text-slate-500">
              No pending approvals
            </div>
            <div v-else class="space-y-3">
              <div v-for="(loan, idx) in pendingLoans" :key="idx" class="p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition">
                <div class="flex justify-between items-start mb-2">
                  <div>
                    <p class="font-bold">{{ loan.memberName }}</p>
                    <p class="text-sm text-slate-600 dark:text-slate-400">Amount: ${{ loan.amount.toLocaleString() }}</p>
                  </div>
                  <span class="text-xs bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 px-2 py-1 rounded">
                    {{ loan.daysWaiting }} days
                  </span>
                </div>
                <div class="flex gap-2">
                  <button class="text-xs px-3 py-1 rounded bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 hover:bg-green-200 dark:hover:bg-green-800 transition">
                    Approve
                  </button>
                  <button class="text-xs px-3 py-1 rounded bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 hover:bg-red-200 dark:hover:bg-red-800 transition">
                    Reject
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-- Recent KYC Verifications -->
          <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
            <h2 class="text-2xl font-bold mb-4 flex items-center">
              <CheckCircle class="w-6 h-6 mr-2 text-blue-600" />
              KYC Verifications Pending
            </h2>
            <div v-if="pendingKYC.length === 0" class="text-center py-8 text-slate-500">
              All KYC verified
            </div>
            <div v-else class="space-y-3">
              <div v-for="(kyc, idx) in pendingKYC" :key="idx" class="p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition">
                <div class="flex justify-between items-start mb-2">
                  <div>
                    <p class="font-bold">{{ kyc.memberName }}</p>
                    <p class="text-sm text-slate-600 dark:text-slate-400">Email: {{ kyc.email }}</p>
                  </div>
                </div>
                <button class="text-xs px-3 py-1 rounded bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 hover:bg-blue-200 dark:hover:bg-blue-800 transition">
                  Review
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Members List -->
        <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
          <h2 class="text-2xl font-bold mb-4 flex items-center">
            <Users class="w-6 h-6 mr-2 text-blue-600" />
            All Members
          </h2>
          <div class="flex gap-2 mb-4">
            <input
              v-model="searchQuery"
              type="text"
              placeholder="Search members..."
              class="flex-1 px-4 py-2 border border-slate-300 dark:border-slate-700 rounded-lg dark:bg-slate-800 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-600"
            />
          </div>
          <div v-if="filteredMembers.length === 0" class="text-center py-8 text-slate-500">
            No members found
          </div>
          <div v-else class="overflow-x-auto">
            <table class="w-full">
              <thead>
                <tr class="border-b border-slate-200 dark:border-slate-700">
                  <th class="text-left py-3 px-4">Name</th>
                  <th class="text-left py-3 px-4">Email</th>
                  <th class="text-left py-3 px-4">Join Date</th>
                  <th class="text-left py-3 px-4">Status</th>
                  <th class="text-left py-3 px-4">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(member, idx) in filteredMembers" :key="idx" class="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800 transition">
                  <td class="py-3 px-4 font-medium">{{ member.name }}</td>
                  <td class="py-3 px-4">{{ member.email }}</td>
                  <td class="py-3 px-4 text-sm">{{ formatDate(member.joinDate) }}</td>
                  <td class="py-3 px-4">
                    <span :class="memberStatusClass(member.status)" class="px-3 py-1 rounded-full text-xs font-medium">
                      {{ member.status }}
                    </span>
                  </td>
                  <td class="py-3 px-4">
                    <button class="text-xs px-3 py-1 rounded bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 transition">
                      View
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Reports Section -->
        <div class="grid md:grid-cols-2 gap-8">
          <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
            <h2 class="text-2xl font-bold mb-4 flex items-center">
              <BarChart3 class="w-6 h-6 mr-2 text-blue-600" />
              Loan Statistics
            </h2>
            <div class="space-y-3">
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Total Disbursed</span>
                <span class="font-bold">${{ stats.totalDisbursed.toLocaleString() }}</span>
              </div>
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Active Loans</span>
                <span class="font-bold">{{ stats.activeLoansCount }}</span>
              </div>
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Default Rate</span>
                <span class="font-bold text-red-600">{{ stats.defaultRate }}%</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-600 dark:text-slate-400">Avg Interest</span>
                <span class="font-bold">{{ stats.avgInterestRate }}%</span>
              </div>
            </div>
          </div>

          <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
            <h2 class="text-2xl font-bold mb-4 flex items-center">
              <PieChart class="w-6 h-6 mr-2 text-blue-600" />
              Member Activity
            </h2>
            <div class="space-y-3">
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Active This Month</span>
                <span class="font-bold">{{ stats.activeThisMonth }}%</span>
              </div>
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Contributions This Month</span>
                <span class="font-bold">${{ stats.contributionsThisMonth.toLocaleString() }}</span>
              </div>
              <div class="flex justify-between pb-2 border-b border-slate-200 dark:border-slate-700">
                <span class="text-slate-600 dark:text-slate-400">Avg Member Balance</span>
                <span class="font-bold">${{ stats.avgMemberBalance.toLocaleString() }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-600 dark:text-slate-400">Retention Rate</span>
                <span class="font-bold text-green-600">{{ stats.retentionRate }}%</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useAuthStore } from "@/_core/stores/authStore";
import { useApi } from "@/composables/useApi";
import Navigation from "@/components/Navigation.vue";
import Footer from "@/components/Footer.vue";
import StatCard from "@/components/StatCard.vue";
import { Briefcase, CheckCircle, Users, BarChart3, PieChart } from "lucide-vue-next";

interface LoanApproval {
  id: string;
  memberName: string;
  amount: number;
  daysWaiting: number;
}

interface KYCVerification {
  id: string;
  memberName: string;
  email: string;
}

interface Member {
  id: string;
  name: string;
  email: string;
  joinDate: string;
  status: "active" | "inactive" | "suspended";
}

const authStore = useAuthStore();
const api = useApi();

const loading = ref(true);
const searchQuery = ref("");

const stats = ref({
  totalMembers: 245,
  totalLoans: 89,
  totalContributions: 125000,
  systemHealth: 98,
  totalDisbursed: 450000,
  activeLoansCount: 67,
  defaultRate: 2.5,
  avgInterestRate: 12.5,
  activeThisMonth: 78,
  contributionsThisMonth: 28500,
  avgMemberBalance: 510,
  retentionRate: 94,
});

const pendingLoans = ref<LoanApproval[]>([
  { id: "1", memberName: "John Doe", amount: 5000, daysWaiting: 5 },
  { id: "2", memberName: "Jane Smith", amount: 3000, daysWaiting: 3 },
  { id: "3", memberName: "Ahmed Hassan", amount: 7500, daysWaiting: 8 },
]);

const pendingKYC = ref<KYCVerification[]>([
  { id: "1", memberName: "Mary Johnson", email: "mary@example.com" },
  { id: "2", memberName: "David Brown", email: "david@example.com" },
]);

const members = ref<Member[]>([
  { id: "1", name: "John Doe", email: "john@example.com", joinDate: "2025-01-15", status: "active" },
  { id: "2", name: "Jane Smith", email: "jane@example.com", joinDate: "2025-02-20", status: "active" },
  { id: "3", name: "Ahmed Hassan", email: "ahmed@example.com", joinDate: "2025-03-10", status: "active" },
  { id: "4", name: "Mary Johnson", email: "mary@example.com", joinDate: "2025-03-05", status: "inactive" },
  { id: "5", name: "David Brown", email: "david@example.com", joinDate: "2025-01-25", status: "active" },
]);

const filteredMembers = computed(() => {
  if (!searchQuery.value) return members.value;
  const query = searchQuery.value.toLowerCase();
  return members.value.filter(
    (m) => m.name.toLowerCase().includes(query) || m.email.toLowerCase().includes(query)
  );
});

const formatDate = (dateStr: string) => {
  return new Date(dateStr).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const memberStatusClass = (status: string) => ({
  "bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200": status === "active",
  "bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200": status === "inactive",
  "bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200": status === "suspended",
});

onMounted(async () => {
  // Fetch admin dashboard data from Laravel backend
  const response = await api.get("/admin/dashboard");
  if (response.success) {
    const data = response.data as any;
    stats.value = {
      totalMembers: data.total_members || 245,
      totalLoans: data.total_loans || 89,
      totalContributions: data.total_contributions || 125000,
      systemHealth: data.system_health || 98,
      totalDisbursed: data.total_disbursed || 450000,
      activeLoansCount: data.active_loans_count || 67,
      defaultRate: data.default_rate || 2.5,
      avgInterestRate: data.avg_interest_rate || 12.5,
      activeThisMonth: data.active_this_month || 78,
      contributionsThisMonth: data.contributions_this_month || 28500,
      avgMemberBalance: data.avg_member_balance || 510,
      retentionRate: data.retention_rate || 94,
    };

    // Load pending loans if available
    if (data.pending_loans) {
      pendingLoans.value = data.pending_loans;
    }

    // Load pending KYC if available
    if (data.pending_kyc) {
      pendingKYC.value = data.pending_kyc;
    }

    // Load members if available
    if (data.members) {
      members.value = data.members;
    }
  }

  loading.value = false;
});
</script>
