// client/src/pages/Home.vue
<template>
  <div class="min-h-screen flex flex-col bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 transition-colors duration-300">
    <!-- Navigation -->
    <Navigation />

    <!-- Hero Section -->
    <Hero />

    <!-- Features Section -->
    <Features />

    <!-- Testimonials Section -->
    <Testimonials />

    <!-- FAQ Section -->
    <FAQ />

    <!-- CTA Section -->
    <CTA />

    <!-- Footer -->
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Navigation from "@/components/Navigation.vue";
import Hero from "@/components/sections/Hero.vue";
import Features from "@/components/sections/Features.vue";
import Testimonials from "@/components/sections/Testimonials.vue";
import FAQ from "@/components/sections/FAQ.vue";
import CTA from "@/components/sections/CTA.vue";
import Footer from "@/components/Footer.vue";
</script>

// client/src/pages/Home.tsx
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";
import { ArrowRight, Users, TrendingUp, Lock, Moon, Sun } from "lucide-react";
import { APP_LOGO, APP_TITLE } from "@/const";
import Navigation from "@/components/Navigation";
import Hero from "@/components/sections/Hero";
import Features from "@/components/sections/Features";
import Testimonials from "@/components/sections/Testimonials";
import FAQ from "@/components/sections/FAQ";
import CTA from "@/components/sections/CTA";
import Footer from "@/components/Footer";

export default function Home() {
  const { user, isAuthenticated, logout } = useAuth();
  const { theme, toggleTheme, switchable } = useTheme();

  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 transition-colors duration-300">
      {/* Navigation */}
      <Navigation user={user} isAuthenticated={isAuthenticated} logout={logout} />

      {/* Hero Section */}
      <Hero />

      {/* Features Section */}
      <Features />

      {/* Testimonials Section */}
      <Testimonials />

      {/* FAQ Section */}
      <FAQ />

      {/* CTA Section */}
      <CTA />

      {/* Footer */}
      <Footer />
    </div>
  );
}
