// client/src/pages/MemberDashboard.vue
<template>
  <div class="min-h-screen flex flex-col">
    <Navigation />

    <div class="flex-1 p-4 sm:p-8 max-w-7xl mx-auto w-full">
      <h1 class="text-4xl font-bold mb-8">Dashboard</h1>

      <div v-if="loading" class="text-center py-12">
        <div class="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        <p class="mt-4 text-slate-600">Loading your dashboard...</p>
      </div>

      <div v-else class="space-y-8">
        <!-- Stats Grid -->
        <div class="grid md:grid-cols-4 gap-4">
          <StatCard title="Total Balance" :value="`$${stats.totalBalance.toLocaleString()}`" icon="DollarSign" />
          <StatCard title="Active Loans" :value="stats.activeLoans" icon="Briefcase" />
          <StatCard title="Contributions" :value="`$${stats.contributions.toLocaleString()}`" icon="TrendingUp" />
          <StatCard title="KYC Status" :value="authStore.user?.kyc_status || 'Not started'" icon="CheckCircle" />
        </div>

        <!-- Quick Actions -->
        <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
          <h2 class="text-2xl font-bold mb-4">Quick Actions</h2>
          <div class="grid md:grid-cols-3 gap-4">
            <button class="p-4 border border-slate-300 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition">
              <TrendingUp class="w-6 h-6 mb-2 mx-auto text-blue-600" />
              <p class="font-bold">Make Contribution</p>
            </button>
            <button class="p-4 border border-slate-300 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition">
              <Briefcase class="w-6 h-6 mb-2 mx-auto text-blue-600" />
              <p class="font-bold">Apply for Loan</p>
            </button>
            <button class="p-4 border border-slate-300 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition">
              <FileText class="w-6 h-6 mb-2 mx-auto text-blue-600" />
              <p class="font-bold">View Documents</p>
            </button>
          </div>
        </div>

        <!-- Recent Transactions -->
        <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
          <h2 class="text-2xl font-bold mb-4">Recent Transactions</h2>
          <div v-if="transactions.length === 0" class="text-center py-8 text-slate-500">
            No transactions yet
          </div>
          <div v-else class="overflow-x-auto">
            <table class="w-full">
              <thead>
                <tr class="border-b border-slate-200 dark:border-slate-700">
                  <th class="text-left py-3 px-4">Date</th>
                  <th class="text-left py-3 px-4">Type</th>
                  <th class="text-left py-3 px-4">Amount</th>
                  <th class="text-left py-3 px-4">Status</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(tx, idx) in transactions" :key="idx" class="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800 transition">
                  <td class="py-3 px-4">{{ formatDate(tx.date) }}</td>
                  <td class="py-3 px-4 font-medium">{{ tx.type }}</td>
                  <td class="py-3 px-4 font-bold">{{ tx.amount > 0 ? '+' : '' }}${{ Math.abs(tx.amount) }}</td>
                  <td class="py-3 px-4">
                    <span :class="statusClass(tx.status)" class="px-3 py-1 rounded-full text-sm font-medium">
                      {{ tx.status }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Active Loans -->
        <div class="bg-white dark:bg-slate-900 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
          <h2 class="text-2xl font-bold mb-4">Active Loans</h2>
          <div v-if="loans.length === 0" class="text-center py-8 text-slate-500">
            No active loans
          </div>
          <div v-else class="space-y-4">
            <div v-for="(loan, idx) in loans" :key="idx" class="p-4 border border-slate-200 dark:border-slate-700 rounded-lg">
              <div class="flex justify-between items-start mb-3">
                <div>
                  <p class="font-bold">Loan Amount: ${{ loan.amount.toLocaleString() }}</p>
                  <p class="text-sm text-slate-600 dark:text-slate-400">Interest Rate: {{ loan.interestRate }}%</p>
                </div>
                <span :class="loanStatusClass(loan.status)" class="px-3 py-1 rounded-full text-sm font-medium">
                  {{ loan.status }}
                </span>
              </div>
              <div class="w-full bg-slate-200 dark:bg-slate-800 rounded-full h-2">
                <div class="bg-blue-600 h-2 rounded-full transition-all" :style="{ width: loan.repaymentProgress + '%' }"></div>
              </div>
              <p class="text-sm text-slate-600 mt-2">{{ loan.repaymentProgress }}% repaid</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useAuthStore } from "@/_core/stores/authStore";
import { useApi } from "@/composables/useApi";
import Navigation from "@/components/Navigation.vue";
import Footer from "@/components/Footer.vue";
import StatCard from "@/components/StatCard.vue";
import { DollarSign, Briefcase, TrendingUp, CheckCircle, FileText } from "lucide-vue-next";

interface Transaction {
  date: string;
  type: string;
  amount: number;
  status: "completed" | "pending" | "failed";
}

interface Loan {
  id: string;
  amount: number;
  interestRate: number;
  repaymentProgress: number;
  status: "active" | "pending" | "completed";
}

const authStore = useAuthStore();
const api = useApi();

const loading = ref(true);
const stats = ref({
  totalBalance: 2500,
  activeLoans: 1,
  contributions: 5000,
  savingsRate: 8.5,
});

const transactions = ref<Transaction[]>([
  { date: "2025-11-10", type: "Contribution", amount: 500, status: "completed" },
  { date: "2025-11-08", type: "Loan Disbursement", amount: 2000, status: "completed" },
  { date: "2025-11-05", type: "Interest Earned", amount: 25, status: "completed" },
]);

const loans = ref<Loan[]>([
  {
    id: "1",
    amount: 2000,
    interestRate: 12,
    repaymentProgress: 35,
    status: "active",
  },
]);

const formatDate = (dateStr: string) => {
  return new Date(dateStr).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const statusClass = (status: string) => ({
  "bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200": status === "completed",
  "bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200": status === "pending",
  "bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200": status === "failed",
});

const loanStatusClass = (status: string) => ({
  "bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200": status === "active",
  "bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200": status === "pending",
  "bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200": status === "completed",
});

onMounted(async () => {
  // Fetch data from Laravel backend
  const response = await api.get("/member/dashboard");
  if (response.success) {
    const data = response.data as any;
    stats.value = {
      totalBalance: data.total_balance || 2500,
      activeLoans: data.active_loans_count || 1,
      contributions: data.total_contributions || 5000,
      savingsRate: data.savings_rate || 8.5,
    };
    
    // Load transactions if available
    if (data.transactions) {
      transactions.value = data.transactions.map((tx: any) => ({
        date: tx.created_at,
        type: tx.type,
        amount: tx.amount,
        status: tx.status,
      }));
    }

    // Load loans if available
    if (data.loans) {
      loans.value = data.loans.map((loan: any) => ({
        id: loan.id,
        amount: loan.amount,
        interestRate: loan.interest_rate,
        repaymentProgress: loan.repayment_progress || 0,
        status: loan.status,
      }));
    }
  }
  
  loading.value = false;
});
</script>

// client/src/pages/MemberDashboard.tsx
import { useAuthContext } from "@/contexts/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import { CreditCard, TrendingUp, PiggyBank, ArrowUpRight, ArrowDownLeft, Plus, Eye, EyeOff, Settings, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";

function MemberDashboardContent() {
  const { user, logout } = useAuthContext();
  const [showBalance, setShowBalance] = useState(true);
  const [activeTab, setActiveTab] = useState("overview");

  // Mock data
  const accountData = {
    totalBalance: 45250.50,
    savingsBalance: 25000.00,
    loanBalance: 8500.00,
    monthlyContribution: 2500.00,
  };

  const recentTransactions = [
    { id: 1, type: "deposit", description: "Monthly Contribution", amount: 2500, date: "Nov 2, 2024", status: "completed" },
    { id: 2, type: "withdrawal", description: "Loan Disbursement", amount: 5000, date: "Oct 28, 2024", status: "completed" },
    { id: 3, type: "interest", description: "Interest Earned", amount: 125.50, date: "Oct 15, 2024", status: "completed" },
    { id: 4, type: "loan_payment", description: "Loan Repayment", amount: 1200, date: "Oct 10, 2024", status: "completed" },
  ];

  const activeLoan = {
    id: "LOAN-2024-001",
    amount: 10000,
    balance: 8500,
    rate: 12.5,
    nextPayment: 1200,
    dueDate: "Nov 15, 2024",
    status: "active",
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950">
      {/* Header */}
      <header className="bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
              Member Dashboard
            </h1>
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Welcome back, {user?.name}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm">
              <Settings className="w-4 h-4 mr-2" />
              Settings
            </Button>
            <Button
              onClick={logout}
              variant="outline"
              size="sm"
              className="text-red-600 dark:text-red-400"
            >
              <LogOut className="w-4 h-4 mr-2" />
              Logout
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Account Overview Cards */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {/* Total Balance */}
          <div className="bg-white dark:bg-slate-900 rounded-lg shadow p-6 border border-slate-200 dark:border-slate-800">
            <div className="flex items-start justify-between mb-4">
              <div>
                <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                  Total Balance
                </p>
                <div className="flex items-center gap-2 mt-2">
                  <p className="text-3xl font-bold text-slate-900 dark:text-white">
                    {showBalance ? `$${accountData.totalBalance.toLocaleString('en-US', { minimumFractionDigits: 2 })}` : "••••••"}
                  </p>
                  <button
                    onClick={() => setShowBalance(!showBalance)}
                    className="p-1 hover:bg-slate-100 dark:hover:bg-slate-800 rounded"
                  >
                    {showBalance ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
                  </button>
                </div>
              </div>
              <div className="p-3 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                <CreditCard className="w-6 h-6 text-blue-600 dark:text-blue-400" />
              </div>
            </div>
          </div>

          {/* Savings Balance */}
          <div className="bg-white dark:bg-slate-900 rounded-lg shadow p-6 border border-slate-200 dark:border-slate-800">
            <div className="flex items-start justify-between mb-4">
              <div>
                <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                  Savings Balance
                </p>
                <p className="text-3xl font-bold text-slate-900 dark:text-white mt-2">
                  ${accountData.savingsBalance.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </p>
              </div>
              <div className="p-3 bg-green-100 dark:bg-green-900/30 rounded-lg">
                <PiggyBank className="w-6 h-6 text-green-600 dark:text-green-400" />
              </div>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Earning 8.5% APY
            </p>
          </div>

          {/* Active Loans */}
          <div className="bg-white dark:bg-slate-900 rounded-lg shadow p-6 border border-slate-200 dark:border-slate-800">
            <div className="flex items-start justify-between mb-4">
              <div>
                <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                  Loan Balance
                </p>
                <p className="text-3xl font-bold text-slate-900 dark:text-white mt-2">
                  ${accountData.loanBalance.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </p>
              </div>
              <div className="p-3 bg-orange-100 dark:bg-orange-900/30 rounded-lg">
                <TrendingUp className="w-6 h-6 text-orange-600 dark:text-orange-400" />
              </div>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              1 active loan
            </p>
          </div>

          {/* Monthly Contribution */}
          <div className="bg-white dark:bg-slate-900 rounded-lg shadow p-6 border border-slate-200 dark:border-slate-800">
            <div className="flex items-start justify-between mb-4">
              <div>
                <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                  Next Contribution
                </p>
                <p className="text-3xl font-bold text-slate-900 dark:text-white mt-2">
                  ${accountData.monthlyContribution.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </p>
              </div>
              <div className="p-3 bg-purple-100 dark:bg-purple-900/30 rounded-lg">
                <ArrowUpRight className="w-6 h-6 text-purple-600 dark:text-purple-400" />
              </div>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Due Nov 30, 2024
            </p>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="grid md:grid-cols-4 gap-4 mb-8">
          <Button className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg flex items-center justify-center gap-2 py-3">
            <Plus className="w-5 h-5" />
            Make Contribution
          </Button>
          <Button variant="outline" className="rounded-lg flex items-center justify-center gap-2 py-3">
            <CreditCard className="w-5 h-5" />
            Apply for Loan
          </Button>
          <Button variant="outline" className="rounded-lg flex items-center justify-center gap-2 py-3">
            <ArrowDownLeft className="w-5 h-5" />
            Withdraw Funds
          </Button>
          <Button variant="outline" className="rounded-lg flex items-center justify-center gap-2 py-3">
            <TrendingUp className="w-5 h-5" />
            View Investments
          </Button>
        </div>

        {/* Tabs */}
        <div className="bg-white dark:bg-slate-900 rounded-lg shadow border border-slate-200 dark:border-slate-800">
          <div className="border-b border-slate-200 dark:border-slate-800">
            <div className="flex">
              {["overview", "transactions", "loans", "contributions"].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-6 py-4 font-medium text-sm transition-colors ${
                    activeTab === tab
                      ? "text-blue-600 dark:text-blue-400 border-b-2 border-blue-600 dark:border-blue-400"
                      : "text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
                  }`}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>
          </div>

          <div className="p-6">
            {activeTab === "overview" && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-4">
                    Active Loan
                  </h3>
                  <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg p-6 border border-slate-200 dark:border-slate-700">
                    <div className="grid md:grid-cols-2 gap-6">
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Loan ID</p>
                        <p className="font-semibold text-slate-900 dark:text-white">{activeLoan.id}</p>
                      </div>
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Original Amount</p>
                        <p className="font-semibold text-slate-900 dark:text-white">${activeLoan.amount.toLocaleString()}</p>
                      </div>
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Remaining Balance</p>
                        <p className="font-semibold text-slate-900 dark:text-white">${activeLoan.balance.toLocaleString()}</p>
                      </div>
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Interest Rate</p>
                        <p className="font-semibold text-slate-900 dark:text-white">{activeLoan.rate}% APR</p>
                      </div>
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Next Payment</p>
                        <p className="font-semibold text-slate-900 dark:text-white">${activeLoan.nextPayment.toLocaleString()}</p>
                      </div>
                      <div>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-1">Due Date</p>
                        <p className="font-semibold text-slate-900 dark:text-white">{activeLoan.dueDate}</p>
                      </div>
                    </div>
                    <Button className="mt-4 bg-blue-600 hover:bg-blue-700">
                      Make Loan Payment
                    </Button>
                  </div>
                </div>
              </div>
            )}

            {activeTab === "transactions" && (
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                  Recent Transactions
                </h3>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-slate-200 dark:border-slate-700">
                        <th className="px-4 py-3 text-left text-sm font-semibold text-slate-900 dark:text-white">
                          Description
                        </th>
                        <th className="px-4 py-3 text-left text-sm font-semibold text-slate-900 dark:text-white">
                          Amount
                        </th>
                        <th className="px-4 py-3 text-left text-sm font-semibold text-slate-900 dark:text-white">
                          Date
                        </th>
                        <th className="px-4 py-3 text-left text-sm font-semibold text-slate-900 dark:text-white">
                          Status
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {recentTransactions.map((txn) => (
                        <tr
                          key={txn.id}
                          className="border-b border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800/50"
                        >
                          <td className="px-4 py-3 text-sm text-slate-900 dark:text-white font-medium">
                            {txn.description}
                          </td>
                          <td className={`px-4 py-3 text-sm font-semibold ${
                            txn.type === "deposit" || txn.type === "interest"
                              ? "text-green-600 dark:text-green-400"
                              : "text-red-600 dark:text-red-400"
                          }`}>
                            {txn.type === "deposit" || txn.type === "interest" ? "+" : "-"}${txn.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                          </td>
                          <td className="px-4 py-3 text-sm text-slate-600 dark:text-slate-400">
                            {txn.date}
                          </td>
                          <td className="px-4 py-3 text-sm">
                            <span className="px-3 py-1 bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-200 rounded-full text-xs font-medium">
                              {txn.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {activeTab === "loans" && (
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                  Your Loans
                </h3>
                <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg p-6 h-96 flex items-center justify-center border border-slate-200 dark:border-slate-700">
                  <p className="text-slate-600 dark:text-slate-400">
                    Detailed loan management interface coming soon
                  </p>
                </div>
              </div>
            )}

            {activeTab === "contributions" && (
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                  Contribution History
                </h3>
                <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg p-6 h-96 flex items-center justify-center border border-slate-200 dark:border-slate-700">
                  <p className="text-slate-600 dark:text-slate-400">
                    Contribution tracking interface coming soon
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

export default function MemberDashboard() {
  return (
    <ProtectedRoute requiredRole="member">
      <MemberDashboardContent />
    </ProtectedRoute>
  );
}
