// client/src/components/Navigation.tsx
import { useState } from "react";
import { Menu, X, Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";
import { APP_LOGO, APP_TITLE } from "@/const";
import { Link } from "wouter";

interface NavigationProps {
  user?: any;
  isAuthenticated?: boolean;
  logout?: () => void;
}

export default function Navigation({ user, isAuthenticated, logout }: NavigationProps) {
  const [isOpen, setIsOpen] = useState(false);
  const { theme, toggleTheme } = useTheme();

  const navLinks = [
    { label: "Home", href: "#home" },
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Blog", href: "#blog" },
    { label: "Contact", href: "#contact" },
  ];

  return (
    <nav className="sticky top-0 z-50 bg-white dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800 shadow-sm">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          {/* Logo */}
          <div className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-blue-800 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-sm">CA</span>
            </div>
            <span className="font-bold text-lg hidden sm:inline text-slate-900 dark:text-white">
              {APP_TITLE || "Coopvest Africa"}
            </span>
          </div>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-8">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className="text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors text-sm font-medium"
              >
                {link.label}
              </a>
            ))}
          </div>

          {/* Right Side Actions */}
          <div className="flex items-center space-x-4">
            {/* Theme Toggle */}
            <button
              onClick={toggleTheme}
              className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              aria-label="Toggle theme"
            >
              {theme === "light" ? (
                <Moon className="w-5 h-5 text-slate-600 dark:text-slate-400" />
              ) : (
                <Sun className="w-5 h-5 text-slate-600 dark:text-slate-400" />
              )}
            </button>

            {/* Auth Buttons */}
            {isAuthenticated ? (
              <div className="flex items-center space-x-3">
                <span className="text-sm text-slate-600 dark:text-slate-300 hidden sm:inline">
                  {user?.email}
                </span>
                <Button
                  onClick={logout}
                  variant="outline"
                  size="sm"
                  className="hidden sm:inline-flex"
                >
                  Logout
                </Button>
                <Button
                  onClick={logout}
                  variant="outline"
                  size="sm"
                  className="sm:hidden"
                >
                  Logout
                </Button>
              </div>
            ) : (
              <div className="hidden md:flex items-center space-x-3">
                <Link href="/login">
                  <Button variant="outline" size="sm" asChild>
                    <span>Login</span>
                  </Button>
                </Link>
                <Link href="/register">
                  <Button size="sm" className="bg-blue-600 hover:bg-blue-700" asChild>
                    <span>Register</span>
                  </Button>
                </Link>
              </div>
            )}

            {/* Mobile Menu Button */}
            <button
              onClick={() => setIsOpen(!isOpen)}
              className="md:hidden p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              {isOpen ? (
                <X className="w-5 h-5" />
              ) : (
                <Menu className="w-5 h-5" />
              )}
            </button>
          </div>
        </div>

        {/* Mobile Navigation */}
        {isOpen && (
          <div className="md:hidden pb-4 space-y-2">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className="block px-4 py-2 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"
              >
                {link.label}
              </a>
            ))}
            {!isAuthenticated && (
              <div className="pt-2 space-y-2 border-t border-slate-200 dark:border-slate-800">
                <Link href="/login">
                  <Button variant="outline" size="sm" className="w-full" asChild>
                    <span>Login</span>
                  </Button>
                </Link>
                <Link href="/register">
                  <Button size="sm" className="w-full bg-blue-600 hover:bg-blue-700" asChild>
                    <span>Register</span>
                  </Button>
                </Link>
              </div>
            )}
          </div>
        )}
      </div>
    </nav>
  );
}

// client/src/components/Navigation.vue
<template>
  <header class="sticky top-0 z-50 bg-white dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800 transition-colors duration-300">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-16">
        <!-- Logo -->
        <RouterLink to="/" class="flex items-center gap-2">
          <img :src="appLogo" :alt="appTitle" class="h-8 w-8" />
          <span class="font-bold text-xl hidden sm:inline">{{ appTitle }}</span>
        </RouterLink>

        <!-- Desktop Navigation -->
        <nav class="hidden md:flex items-center gap-8">
          <RouterLink to="/" class="hover:text-blue-600 dark:hover:text-blue-400 transition">Home</RouterLink>
          <RouterLink to="/about" class="hover:text-blue-600 dark:hover:text-blue-400 transition">About</RouterLink>
          <a href="#services" class="hover:text-blue-600 dark:hover:text-blue-400 transition">Services</a>
          <a href="#faq" class="hover:text-blue-600 dark:hover:text-blue-400 transition">FAQ</a>
        </nav>

        <!-- Right Section -->
        <div class="flex items-center gap-4">
          <!-- Theme Toggle -->
          <button
            @click="themeStore.toggleTheme"
            class="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition"
            :title="themeStore.isDark ? 'Switch to light mode' : 'Switch to dark mode'"
          >
            <Sun v-if="themeStore.isDark" class="w-5 h-5" />
            <Moon v-else class="w-5 h-5" />
          </button>

          <!-- Auth Buttons -->
          <div v-if="!authStore.isAuthenticated" class="flex gap-2">
            <RouterLink to="/login" class="px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-900 transition">
              Login
            </RouterLink>
            <RouterLink to="/register" class="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition">
              Sign Up
            </RouterLink>
          </div>

          <div v-else class="flex gap-2 items-center">
            <span class="text-sm">{{ authStore.user?.name }}</span>
            <button
              @click="authStore.logout"
              class="px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-900 transition"
            >
              Logout
            </button>
          </div>

          <!-- Mobile Menu Button -->
          <button class="md:hidden p-2">
            <Menu class="w-6 h-6" />
          </button>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { useRouter, RouterLink } from "vue-router";
import { useAuthStore } from "@/_core/stores/authStore";
import { useThemeStore } from "@/_core/stores/themeStore";
import { APP_LOGO, APP_TITLE } from "@/const";
import { Sun, Moon, Menu } from "lucide-vue-next";

const authStore = useAuthStore();
const themeStore = useThemeStore();

const appLogo = APP_LOGO;
const appTitle = APP_TITLE;
</script>
